feat(EpochBasedInflationaryVoteToken): test inflation from multiple delegatees
MZero-Labs/ttg pull request #262
Opened 2024-03-28 01:12 UTC by PierrickGT

Issue: https://github.com/sherlock-audit/2023-10-mzero-judging/issues/64

This PR add a test illustrating the scenario outlined by the warden and invalidates the described issue.

2024-04-12 17:48 UTC, deluca-mike requested changes

2024-04-12 21:38 UTC, PierrickGT commented on src/abstract/EpochBasedInflationaryVoteToken.sol
> +        //       and looping through the subsequent epochs until `lastEpoch_` to get the unrealized inflation.
Fixed in: https://github.com/MZero-Labs/ttg/pull/262/commits/afa804a9e84d422fde84b12cbb19284a025eb420

2024-04-12 21:38 UTC, PierrickGT commented on src/abstract/EpochBasedInflationaryVoteToken.sol
> +        //       since the inflation is realized by syncing in the `_delegate()` function.
Fixed in: https://github.com/MZero-Labs/ttg/pull/262/commits/afa804a9e84d422fde84b12cbb19284a025eb420

2024-04-12 21:38 UTC, PierrickGT commented on src/abstract/EpochBasedInflationaryVoteToken.sol
> +     *        before setting `newDelegatee_` as the delegatee.
Fixed in: https://github.com/MZero-Labs/ttg/pull/262/commits/afa804a9e84d422fde84b12cbb19284a025eb420

2024-04-12 21:40 UTC, PierrickGT commented on test/Registrar.t.sol
> -    function test_initialState() external view {
It is failing to compile otherwise.

2024-04-17 07:55 UTC, deluca-mike approved these changes

2024-04-17 07:55 UTC, deluca-mike commented on test/Registrar.t.sol
> -    function test_initialState() external view {
Odd

2024-04-17 14:59 UTC, merged