feat: Deployment getters and tests
MZero-Labs/ttg pull request #268
Opened 2024-04-17 07:59 UTC by deluca-mike

2024-04-17 19:52 UTC, PierrickGT requested changes

2024-04-17 19:52 UTC, PierrickGT commented on test/Deploy.t.sol
> +        // Power Token assertions
We can also check that the cash token was properly set.

2024-04-17 19:52 UTC, PierrickGT commented on test/Deploy.t.sol
> +        // Zero Token assertions
We could also check the initial balances per account.

2024-04-17 19:52 UTC, PierrickGT commented on test/Deploy.t.sol
> +        // Power Token Deployer assertions
We could also check the initial balances per account.

2024-04-23 14:53 UTC, PierrickGT approved these changes

2024-04-24 16:07 UTC, toninorair approved these changes

2024-04-24 16:21 UTC, merged